# -*- coding: utf-8 -*-
"""Healthcare Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PSDTQWzhCAvndzdshQz014F6AmgZ4UUg
"""

# ==========================================
# Healthcare Resource Optimization Project
# ==========================================

# Data Manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Ignore Warnings
import warnings
warnings.filterwarnings('ignore')

# Display all columns
pd.set_option('display.max_columns', None)

# Machine Learning
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("/content/healthcare-dataset-stroke-data.csv")

df.head()

df.tail()

df.sample(10)

print("Shape of Dataset :", df.shape)

print(df.info())

df.columns

df.dtypes

df.describe(include='object')

df.isnull().sum()

(df.isnull().sum()/len(df))*100

#checking duplicates
df.duplicated().sum()

#removing duplicates
df.drop_duplicates(inplace=True)

#checking again
df.duplicated().sum()

for col in df.columns:
    print("-"*40)
    print(col)
    print(df[col].unique())
df.nunique()

# BMI containg missing values
df['bmi'].isnull().sum()

#Filling Missing BMI values using median
df['bmi'].fillna(df['bmi'].median(), inplace=True)

df.isnull().sum()

#removing Pateint Id Column
df.drop("id", axis=1, inplace=True)

#checking class distribution
df['stroke'].value_counts()
#changing it to percentage
df['stroke'].value_counts(normalize=True)*100

#seprating numerical and categorical columns
numerical_columns = df.select_dtypes(include=['int64','float64']).columns

categorical_columns = df.select_dtypes(include=['object']).columns

print("Numerical Columns")
print(numerical_columns)

print()

print("Categorical Columns")
print(categorical_columns)

#checking outliers
plt.figure(figsize=(15,6))

for i,col in enumerate(numerical_columns):
    plt.subplot(2,3,i+1)
    sns.boxplot(df[col])

plt.tight_layout()
plt.show()

#Remove Extreme Outliers Using IQR
def remove_outliers(data, column):

    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)

    IQR = Q3-Q1

    lower = Q1-1.5*IQR
    upper = Q3+1.5*IQR

    return data[(data[column]>=lower) & (data[column]<=upper)]

df = remove_outliers(df,'bmi')
df = remove_outliers(df,'avg_glucose_level')

print(df.shape)

df.head()

label_encoder = LabelEncoder()

for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col])

df.head()

corr = df.corr()

corr

# Reload original dataset for visualization
import pandas as pd

eda_df = pd.read_csv("/content/healthcare-dataset-stroke-data.csv")

# Fill missing BMI values
eda_df['bmi'].fillna(eda_df['bmi'].median(), inplace=True)

plt.style.use('ggplot')
sns.set(font_scale=1.0)

#stroke distribution
plt.figure(figsize=(6,5))
sns.countplot(x='stroke', data=eda_df, palette='Set2')
plt.title("Stroke Distribution")
plt.xlabel("Stroke")
plt.ylabel("Count")
plt.show()

#gender distribution & pie chart
plt.figure(figsize=(6,5))
sns.countplot(x='gender', data=eda_df, palette='pastel')
plt.title("Gender Distribution")
plt.show()

eda_df['gender'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    figsize=(6,6)
)

plt.ylabel("")
plt.title("Gender Percentage")
plt.show()

#Age Distribution
plt.figure(figsize=(8,5))
sns.histplot(eda_df['age'], bins=30, kde=True, color='skyblue')
plt.title("Age Distribution")
plt.show()

#bmi Distribution
plt.figure(figsize=(8,5))
sns.histplot(eda_df['bmi'], bins=30, kde=True, color='green')
plt.title("BMI Distribution")
plt.show()

#Average Glucose level Distribution

plt.figure(figsize=(8,5))
sns.histplot(
    eda_df['avg_glucose_level'],
    bins=30,
    kde=True,
    color='orange'
)

plt.title("Average Glucose Level")
plt.show()

# AGE vs sTROKE

plt.figure(figsize=(8,5))
sns.boxplot(x='stroke', y='age', data=eda_df)
plt.title("Age vs Stroke")
plt.show()

#BMI VS sTROKE
plt.figure(figsize=(8,5))
sns.boxplot(x='stroke', y='bmi', data=eda_df)
plt.title("BMI vs Stroke")
plt.show()

# Glucose Level vs Stroke
plt.figure(figsize=(8,5))
sns.boxplot(x='stroke',
            y='avg_glucose_level',
            data=eda_df)

plt.title("Average Glucose vs Stroke")
plt.show()

# HYPERTENSION VS STROKE

plt.figure(figsize=(7,5))
sns.countplot(
    x='hypertension',
    hue='stroke',
    data=eda_df
)

plt.title("Hypertension vs Stroke")
plt.show()

#HEART DISEASE VS STROKE

plt.figure(figsize=(7,5))
sns.countplot(
    x='heart_disease',
    hue='stroke',
    data=eda_df
)

plt.title("Heart Disease vs Stroke")
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(
    x='smoking_status',
    data=eda_df
)

plt.xticks(rotation=20)
plt.title("Smoking Status")
plt.show()

#SMOKING VS STROKE

plt.figure(figsize=(10,5))
sns.countplot(
    x='smoking_status',
    hue='stroke',
    data=eda_df
)

plt.xticks(rotation=20)
plt.title("Smoking Status vs Stroke")
plt.show()

plt.figure(figsize=(9,5))
sns.countplot(
    x='work_type',
    data=eda_df
)

plt.xticks(rotation=20)
plt.title("Work Type")
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(
    x='work_type',
    hue='stroke',
    data=eda_df
)

plt.xticks(rotation=20)
plt.title("Work Type vs Stroke")
plt.show()

plt.figure(figsize=(6,5))
sns.countplot(
    x='Residence_type',
    data=eda_df
)

plt.title("Residence Type")
plt.show()

plt.figure(figsize=(7,5))
sns.countplot(
    x='Residence_type',
    hue='stroke',
    data=eda_df
)

plt.title("Residence Type vs Stroke")
plt.show()

plt.figure(figsize=(7,5))
sns.countplot(
    x='ever_married',
    hue='stroke',
    data=eda_df
)

plt.title("Marriage vs Stroke")
plt.show()

sns.pairplot(
    eda_df[
        ['age',
         'bmi',
         'avg_glucose_level',
         'stroke']
    ],
    hue='stroke'
)

plt.show()

from sklearn.preprocessing import LabelEncoder

temp = eda_df.copy()

encoder = LabelEncoder()

for col in temp.select_dtypes(include='object').columns:
    temp[col] = encoder.fit_transform(temp[col])

plt.figure(figsize=(12,8))

sns.heatmap(
    temp.corr(),
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")
plt.show()

plt.figure(figsize=(8,5))
sns.violinplot(
    x='stroke',
    y='age',
    data=eda_df
)

plt.show()

plt.figure(figsize=(8,5))

sns.scatterplot(
    x='age',
    y='avg_glucose_level',
    hue='stroke',
    data=eda_df
)

plt.show()

plt.figure(figsize=(8,5))

sns.kdeplot(
    eda_df['age'],
    shade=True
)

plt.title("Age Density")
plt.show()

eda_df.hist(
    figsize=(14,10),
    bins=20
)

plt.tight_layout()
plt.show()

stroke = eda_df['stroke'].value_counts()

plt.figure(figsize=(6,6))

plt.pie(
    stroke,
    labels=['No Stroke','Stroke'],
    autopct='%1.1f%%'
)

plt.title("Stroke Percentage")
plt.show()

eda_df.groupby('stroke')['age'].mean()

eda_df.groupby('stroke')['bmi'].mean()

eda_df.groupby('stroke')['avg_glucose_level'].mean()

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

df.to_csv("Cleaned_Healthcare_Data.csv", index=False)

df = pd.read_csv("Cleaned_Healthcare_Data.csv")

df.info()

df.isnull().sum()

#CREATING AGE GROUP

df['Age_Group'] = pd.cut(
    df['age'],
    bins=[0,18,35,50,65,100],
    labels=[
        'Child',
        'Young Adult',
        'Adult',
        'Middle Age',
        'Senior' ]
)

df[['age','Age_Group']].head()

df['BMI_Category'] = pd.cut(
    df['bmi'],
    bins=[0,18.5,25,30,100],
    labels=[
        'Underweight',
        'Normal',
        'Overweight',
        'Obese'
    ]
)


df[['bmi','BMI_Category']].head()



df['Glucose_Category'] = pd.cut(
    df['avg_glucose_level'],
    bins=[0,100,140,200,400],
    labels=[
        'Normal',
        'Prediabetes',
        'Diabetes',
        'Severe'
    ]
)

df[['avg_glucose_level','Glucose_Category']].head()

encoder = LabelEncoder()

df['Age_Group'] = encoder.fit_transform(df['Age_Group'])

df['BMI_Category'] = encoder.fit_transform(df['BMI_Category'])

df['Glucose_Category'] = encoder.fit_transform(df['Glucose_Category'])

df.head()

X = df.drop('stroke', axis=1)

y = df['stroke']

print(X.columns)

y.head()

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns
)

X_scaled.head()

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Features :", X_train.shape)

print("Testing Features :", X_test.shape)

print("Training Labels :", y_train.shape)

print("Testing Labels :", y_test.shape)

print(y_train.value_counts())

!pip install imbalanced-learn

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train,
    y_train
)

print(y_train_smote.value_counts())

print(X_train_smote.shape)

print(y_train_smote.shape)

processed = X_scaled.copy()

processed['stroke'] = y.values

processed.to_csv(
    "Processed_Healthcare_Data.csv",
    index=False
)

import joblib

joblib.dump(
    scaler,
    "HealthcareScaler.pkl"
)

X_scaled.describe()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(15,10))

sns.heatmap(
    df.corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Matrix After Feature Engineering")

plt.show()

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)

rf.fit(X_train_smote, y_train_smote)

importance = pd.DataFrame({
    'Feature':X.columns,
    'Importance':rf.feature_importances_
})

importance.sort_values(
    by='Importance',
    ascending=False,
    inplace=True)

importance.head(10)

plt.figure(figsize=(10,6))

sns.barplot(
    data=importance.head(10),
    x='Importance',
    y='Feature'
)

plt.title("Top 10 Important Features")

plt.show()

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.metrics import accuracy_score

print(X_train_smote.shape)
print(y_train_smote.shape)

print(X_test.shape)
print(y_test.shape)

models = {

    "Logistic Regression":
        LogisticRegression(random_state=42),

    "Decision Tree":
        DecisionTreeClassifier(random_state=42),

    "Random Forest":
        RandomForestClassifier(
            n_estimators=200,
            random_state=42
        ),

    "KNN":
        KNeighborsClassifier(n_neighbors=5),

    "SVM":
        SVC(
            probability=True,
            random_state=42
        ),

    "Naive Bayes":
        GaussianNB(),

    "Gradient Boosting":
        GradientBoostingClassifier(
            random_state=42
        )
}

trained_models = {}

for name, model in models.items():

    model.fit(X_train_smote, y_train_smote)

    trained_models[name] = model

print("All models trained successfully!")

predictions = {}

for name, model in trained_models.items():

    predictions[name] = model.predict(X_test)

accuracy = {}

for name in predictions:

    accuracy[name] = accuracy_score(
        y_test,
        predictions[name]
    )

accuracy

accuracy_df = pd.DataFrame({

    "Model":accuracy.keys(),

    "Accuracy":accuracy.values()

})

accuracy_df

accuracy_df = accuracy_df.sort_values(

    by="Accuracy",

    ascending=False

)

accuracy_df

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,6))

sns.barplot(

    data=accuracy_df,

    x="Accuracy",

    y="Model"

)

plt.title("Machine Learning Model Comparison")

plt.show()

log_model = LogisticRegression(random_state=42)

log_model.fit(
    X_train_smote,
    y_train_smote
)

log_pred = log_model.predict(X_test)

log_accuracy = accuracy_score(
    y_test,
    log_pred
)

print(log_accuracy)

dt = DecisionTreeClassifier(
    random_state=42
)

dt.fit(
    X_train_smote,
    y_train_smote
)

dt_pred = dt.predict(X_test)

dt_accuracy = accuracy_score(
    y_test,
    dt_pred
)

print(dt_accuracy)

rf = RandomForestClassifier(

    n_estimators=200,

    random_state=42

)

rf.fit(

    X_train_smote,

    y_train_smote

)

rf_pred = rf.predict(X_test)

rf_accuracy = accuracy_score(

    y_test,

    rf_pred

)

print(rf_accuracy)

comparison = pd.DataFrame({

    "Model":[

        "Logistic Regression",

        "Decision Tree",

        "Random Forest"

    ],

    "Accuracy":[

        log_accuracy,

        dt_accuracy,

        rf_accuracy,

    ]

})

comparison

comparison.sort_values(

    by="Accuracy",

    ascending=False,

    inplace=True

)

comparison

plt.figure(figsize=(12,6))

sns.barplot(

    data=comparison,

    x="Accuracy",

    y="Model"

)

plt.title("Performance Comparison of ML Models")

plt.xlabel("Accuracy")

plt.ylabel("Model")

plt.show()

import joblib

best_model = rf

joblib.dump(

    best_model,

    "Healthcare_Stroke_Model.pkl"

)

print("Best model saved successfully.")

best_model_name = comparison.iloc[0]["Model"]

best_models = {
    "Logistic Regression": log_model,
    "Decision Tree": dt,
    "Random Forest": rf
}

joblib.dump(best_models[best_model_name], "Best_Healthcare_Model.pkl")
print(f"Saved best model: {best_model_name}")

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_curve,
    roc_auc_score,
    precision_recall_curve
)

from sklearn.model_selection import cross_val_score

best_model = rf

y_pred = best_model.predict(X_test)

y_prob = best_model.predict_proba(X_test)[:,1]

accuracy = accuracy_score(y_test,y_pred)

print("Accuracy :",accuracy)

precision = precision_score(y_test,y_pred)

print("Precision :",precision)

recall = recall_score(y_test,y_pred)

print("Recall :",recall)

f1 = f1_score(y_test,y_pred)

print("F1 Score :",f1)

print(classification_report(y_test,y_pred))

cm = confusion_matrix(y_test,y_pred)

cm

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    cmap="Blues",
    fmt="d"
)

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.title("Confusion Matrix")

plt.show()

scores = cross_val_score(

    rf,

    X_scaled,

    y,

    cv=10,

    scoring="accuracy"

)

scores

print("Average Accuracy")

print(scores.mean())

# @title
print(scores.std())

plt.figure(figsize=(8,5))

plt.plot(

    range(1,11),

    scores,

    marker='o'

)

plt.title("Cross Validation Accuracy")

plt.xlabel("Fold")

plt.ylabel("Accuracy")

plt.show()

from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

results = []

for name,model in trained_models.items():

    pred = model.predict(X_test)

    acc = accuracy_score(y_test,pred)

    pre = precision_score(y_test,pred)

    rec = recall_score(y_test,pred)

    f1 = f1_score(y_test,pred)

    results.append([

        name,

        acc,

        pre,

        rec,

        f1

    ])

evaluation = pd.DataFrame(

    results,

    columns=[

        "Model",

        "Accuracy",

        "Precision",

        "Recall",

        "F1 Score"

    ]

)

evaluation

evaluation.sort_values(

    by="Accuracy",

    ascending=False,

    inplace=True
)

evaluation

plt.figure(figsize=(10,6))

sns.barplot(

    data=evaluation,

    x="F1 Score",

    y="Model"

)

plt.title("F1 Score Comparison")

plt.show()

importance = pd.DataFrame({

    "Feature":X.columns,

    "Importance":rf.feature_importances_

})

importance = importance.sort_values(

    by="Importance",

    ascending=False
)

importance



evaluation.style.background_gradient(
    cmap="Greens"
)

best = evaluation.iloc[0]

print(best)

df = pd.read_csv("/content/healthcare-dataset-stroke-data.csv")

risk_probability = rf.predict_proba(X_scaled)[:,1]

processed['Risk_Probability'] = risk_probability

def classify_risk(prob):

    if prob < 0.30:
        return "Low Risk"

    elif prob < 0.60:
        return "Medium Risk"

    elif prob < 0.80:
        return "High Risk"

    else:
        return "Critical"

df["Risk_Level"] = processed["Risk_Probability"].apply(classify_risk)

processed['Risk_Probability'].head()

df['Risk_Level'].head()

risk_summary = df['Risk_Level'].value_counts()

print(risk_summary)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))

sns.countplot(
    x='Risk_Level',
    data=df,
    order=['Low Risk','Medium Risk','High Risk','Critical']
)

plt.title("Patient Risk Categories")

plt.show()

icu_required = len(df[df['Risk_Level']=="Critical"])

print("ICU Beds Required =",icu_required)

observation = len(df[df['Risk_Level']=="High Risk"])

print("Observation Beds =",observation)

emergency = len(

df[df['Risk_Level'].isin(['Critical','High Risk'])]

)

print("Emergency Patients =",emergency)

doctors = np.ceil(emergency/20)

print("Doctors Required =",int(doctors))

nurses = np.ceil(emergency/8)

print("Nurses Required =",int(nurses))

ambulance = np.ceil(emergency/12)

print("Ambulances Required =",int(ambulance))

capacity = 500

occupancy = (len(df)/capacity)*100

print(occupancy)

if occupancy<50:

    print("Hospital Under-utilized")

elif occupancy<80:

    print("Hospital Operating Normally")

else:

    print("Hospital Near Full Capacity")

high_risk = df[df["Risk_Level"]=="Critical"]

high_risk.head()

risk_age = df.groupby("Risk_Level")["age"].mean()

risk_age

risk_bmi = df.groupby("Risk_Level")["bmi"].mean()

risk_bmi

risk_glucose = df.groupby(

"Risk_Level"

)["avg_glucose_level"].mean()

risk_glucose

risk_summary.plot(

kind='pie',

autopct="%1.1f%%",

figsize=(6,6)

)

plt.ylabel("")

plt.title("Risk Distribution")

plt.show()

plt.figure(figsize=(8,5))

risk_summary.plot(kind='bar')

plt.title("Risk Distribution")

plt.show()

dashboard = pd.DataFrame({

"Metric":[

"Total Patients",

"Critical Patients",

"High Risk",

"Medium Risk",

"Low Risk",

"ICU Beds",

"Doctors",

"Nurses",

"Ambulances"

],

"Value":[

len(df),

len(df[df.Risk_Level=="Critical"]),

len(df[df.Risk_Level=="High Risk"]),

len(df[df.Risk_Level=="Medium Risk"]),

len(df[df.Risk_Level=="Low Risk"]),

icu_required,

int(doctors),

int(nurses),

int(ambulance)

]

})

dashboard

dashboard.to_csv(

"Hospital_Dashboard.csv",

index=False

)

plt.figure(figsize=(10,6))

sns.barplot(

data=dashboard,

x="Metric",

y="Value"

)

plt.xticks(rotation=45)

plt.title("Hospital Resource Dashboard")

plt.show()

import plotly.express as px

fig = px.bar(

dashboard,

x='Metric',

y='Value',

title='Healthcare Resource Dashboard'

)

fig.show()

import seaborn as sns

plt.figure(figsize=(15,10))

sns.heatmap(

    processed.corr(),

    annot=True,

    cmap="RdYlGn"

)

plt.show()

critical = processed.sort_values(

by="Risk_Probability",

ascending=False

)

critical.head(20)

critical.head(20).to_csv(

"Critical_Patients.csv",

index=False

)

recommendation = []

if icu_required>40:

    recommendation.append("Increase ICU Beds")

if doctors>15:

    recommendation.append("Hire Additional Doctors")

if nurses>25:

    recommendation.append("Increase Nursing Staff")

if ambulance>8:

    recommendation.append("Deploy Extra Ambulances")

recommendation

print("Hospital Recommendations")

for i in recommendation:

    print(i)

print("="*60)

print("HEALTHCARE RESOURCE OPTIMIZATION REPORT")

print("="*60)

print("Total Patients :",len(df))

print("Critical Patients :",icu_required)

print("High Risk Patients :",observation)

print("Doctors Required :",int(doctors))

print("Nurses Required :",int(nurses))

print("Ambulances Required :",int(ambulance))

print("Hospital Occupancy :",round(occupancy,2),"%")

print("="*60)

q1 = processed["Risk_Probability"].quantile(0.50)
q2 = processed["Risk_Probability"].quantile(0.75)
q3 = processed["Risk_Probability"].quantile(0.90)

def classify_risk(prob):
    if prob <= q1:
        return "Low Risk"
    elif prob <= q2:
        return "Medium Risk"
    elif prob <= q3:
        return "High Risk"
    else:
        return "Critical"

df["Risk_Level"] = processed["Risk_Probability"].apply(classify_risk)